apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::078427121643:role/eksctl-eksctl-demo-nodegroup-ng-3-NodeInstanceRole-1JNKKP1KEQR05
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::078427121643:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-27T10:12:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3965"
  uid: 9b66d7b6-c123-40b7-82ef-ae55cf72c3ee
